### PR TITLE
Contribution update

### PR DESCRIPTION
**Pull request by vanderaj**
This updates the text. I've not yet been able to validate all the instructions, so please keep this PR open until after I've made it work.

### CODE REVIEW

**Comment by SayakMukhopadhyay** [comment]
@vanderaj Let me know once this PR is ready to merge

**Comment by vanderaj** [comment]
Sorry, with getting third Cmdr ready for Colonia and work, I haven't had time to update. I'll try to get it done this afternoon

**Comment by SayakMukhopadhyay** [comment]
No worries, take your time

**Comment by vanderaj** [comment]
This is ready for review and commit

**Comment by vanderaj** [comment]
This is ready for review and verification by a new person

**Pull request merged**
